title: Photos
description: Open source "alternative" to Google Photos. Maintained by Gavin D'souza
email: me@gavv.in
url: https://photos.gavv.in
author:
  name: Gavin D'souza
  url: https://gavv.in/

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
